#!/bin/bash

# Author: MD Arafat Kabir
# Description: Base code generated by ChatGPT, prompted and modified by the author.

# Define color codes
DEFAULT_COLOR="\033[0m"  # Reset color
BLACK_COLOR="\033[30m"   # Black text
RED_COLOR="\033[31m"     # Red text
GREEN_COLOR="\033[32m"   # Green text
YELLOW_COLOR="\033[33m"  # Yellow text
BLUE_COLOR="\033[34m"    # Blue text
MAGENTA_COLOR="\033[35m" # Magenta text
CYAN_COLOR="\033[36m"    # Cyan text
WHITE_COLOR="\033[37m"   # White text


# Function to display usage information
usage() {
  echo "Usage: colorfilt.sh [-h] [-c COLOR]"
  echo "Reads text from stdin and pipes it to stdout with optional text color."
  echo "Options:"
  echo "  -c COLOR   Specify the text color. "
  echo "             Options: black, red, green, yellow, blue, magenta, cyan, white, default is green."
  echo "  -h         Print this usage information."
}


# Default color
COLOR="$GREEN_COLOR"
PRINT_USAGE=0

# Check for optional arguments
while getopts "c:h" opt; do
  case "$opt" in
    c)
      case "$OPTARG" in
        "black")
          COLOR="$BLACK_COLOR"
          ;;
        "red")
          COLOR="$RED_COLOR"
          ;;
        "green")
          COLOR="$GREEN_COLOR"
          ;;
        "yellow")
          COLOR="$YELLOW_COLOR"
          ;;
        "blue")
          COLOR="$BLUE_COLOR"
          ;;
        "magenta")
          COLOR="$MAGENTA_COLOR"
          ;;
        "cyan")
          COLOR="$CYAN_COLOR"
          ;;
        "white")
          COLOR="$WHITE_COLOR"
          ;;
        *)
          usage
          exit 1
          ;;
      esac
      ;;
    h)
      PRINT_USAGE=1
      ;;
    \?)
      usage
      exit 1
      ;;
  esac
done


# If -h switch is specified, print usage and exit
if [ $PRINT_USAGE -eq 1 ]; then
  usage
  exit 0
fi


# Read input from stdin line by line and print it immediately
while IFS= read -r line; do
  echo -ne "${COLOR}"            # Set the line color
  echo -e  "${line}"
  echo -ne "${DEFAULT_COLOR}"    # Reset the color
done

